version: '2'
services:
  database:
    image: mysql:5.7
    ports:
       - "3308:3306"
    expose:
       - "3306"
    volumes:
       - /vol/dietoterapia/db:/var/lib/mysql:rw
    environment:
       MYSQL_ROOT_PASSWORD: "senha"
       MYSQL_DATABASE: "dieta"

  dietoterapiaApi:
    container_name: dietoterapiaApi
    build:
      context: .
      dockerfile: Dockerfile_api
    image: dietoterapia_api:latest
    depends_on:
      - "database"
    expose:
      - "8080"
    ports:
      - "8082:8080"




