FROM anapsix/alpine-java:8

# Copy and install

COPY apache-tomcat-8.5.34.tar.gz .
RUN  tar -xvf apache-tomcat-8.5.34.tar.gz -C /opt/
 # rm -f apache-tomcat-8.5.34.tar.gz apache-tomcat-8.5.34.tar.gz.sha512 &&\
 # ln -s /opt/apache-tomcat-${TOMCAT_VERSION_FULL} /opt/tomcat &&\
 # rm -rf /opt/tomcat/webapps/examples /opt/tomcat/webapps/docs &&\
 # rm -rf /var/cache/apk/*

# Configuration
ADD tomcat-users.xml /opt/apache-tomcat-8.5.34/conf/
ADD context.xml /opt/apache-tomcat-8.5.34/webapps/host-manager/META-INF/
ADD context.xml /opt/apache-tomcat-8.5.34/webapps/manager/META-INF/

ADD target/dieta-api.war /opt/tomcat/webapps
#RUN sed -i 's/52428800/5242880000/g' /opt/tomcat/webapps/manager/WEB-INF/web.xml

# Set environment
ENV CATALINA_HOME /opt/apache-tomcat-8.5.34

# Launch Tomcat on startup
CMD ${CATALINA_HOME}/bin/catalina.sh run